ecorpin_corp/ecorpin/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'ecorpin'
urlpatterns = [
    path('', views.index_ecorpin, name='index'),
    path('service/', views.service, name='service'),
    path('feedback/', views.feedback_create, name='feedback'),
    path('about/', views.about, name='about'),
    path('careers/', views.careers, name='careers'),
    path('contact/', views.contact, name='contact'),
    path('terms_of_use/', views.tou, name='tou'),
    path('team/', views.team, name='team'),
    path('privacy/', views.privacy, name='privacy'),
    path('server_maintenance/', views.maintenance, name='maintenance'),
    path('covid/', views.covid, name='covid'),
]

ecorpin_corp/ecorpin_corp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

# favicon view of the web server
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('ecorpin.urls')),
    path('', include('service_access.urls')),
    path('', include('bbit.urls')),
    path('', include('works.urls')),
    path('', include('payment.urls')),
    path('', include('lab.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecorpin_corp/lab/urls.py
from django.urls import path

from .views import index 

app_name = 'lab'

urlpatterns = [
    path('lab', index, name="index"),
]

ecorpin_corp/service_access/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url 

# import views here
from . import views

app_name = 'service_access'
urlpatterns = [
    path('contact_request/', views.contact_request, name='contact_request'),
    path('service_login/', views.login_view, name="login"),
    path('logout/', views.service_logout, name="logout"),
    path('dashboard/', views.ServiceDashboard.as_view(), name="dashboard"),
    path('profile/', views.ServiceUserProfile.as_view(), name="profile"),
]

ecorpin_corp/works/urls.py
from django.urls import path
from . import views

app_name = 'works'
urlpatterns = [
    path('work/', views.projects_view, name='projects'),

]

ecorpin_corp/ecorpin/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
#----------------------------S-P-O-T-L-I-G-H-T
class Spotlight(models.Model):
    spotlight_info = models.CharField(max_length=600)
    spotlight_text = models.CharField(max_length=600)
    spotlight_date = models.DateTimeField('Date Published')

    def __str__(self):
        return self.spotlight_info
    
    def was_published_recently(self):
        return self.spotlight_date >= timezone.now() - datetime.timedelta(days=1)

#----------------------------E-N-D-P-O-I--N-T
class Endpoint_info(models.Model):
    title = models.CharField(max_length=20)
    end_point = models.CharField(max_length=50)
    sideNav = models.CharField(max_length=20)
    main_headBox = models.CharField(max_length=500)
    edge_headBox = models.CharField(max_length=200)
    
    def __str__(self):
        return self.end_point

#----------------------------E-C-O-R-P-I-A-N
class Ecorpian(models.Model):
    name = models.CharField(max_length=50)
    designation = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    office_address = models.CharField(max_length=100)
    message = models.TextField()
    joinDate = models.DateTimeField('Joining Date')
    
    def __str__(self):
        return self.name

#----------------------------F-E-E-D-B-A-C-K
class Feedback(models.Model):
    visitor_name = models.CharField(max_length=50)
    visitor_organization = models.CharField(max_length=100)
    visitor_email = models.EmailField()
    feedback_msg = models.TextField()

    def __str__(self):
        return self.visitor_email

class EcorpinStat(models.Model):
    client_stat = models.IntegerField()
    project_stat = models.IntegerField()
    service_stat = models.IntegerField()

ecorpin_corp/ecorpin/forms.py
from django import forms

from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('visitor_name', 'visitor_organization', 'visitor_email', 'feedback_msg')
        labels = {
            'visitor_name':'Full Name',
            'visitor_organization':'Company/Organization',
            'visitor_email':'Email Address',
            'feedback_msg':'Feedback/Suggestion/Idea Message'
        }
        
        #exclude = ['feedback_Date'] #feedback date and time label

ecorpin_corp/ecorpin/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect


from django.utils import timezone

from .models import Spotlight, Endpoint_info, Ecorpian, Feedback

from .forms import FeedbackForm

# Create your views here.
def fevicon_ecorpin(request):
    # Return the fevicon asset
    pass

def index_ecorpin(request):
    spotlightData = Spotlight.objects.all().latest('spotlight_date')
    context = {
        'latest_spotlight': spotlightData,
    }
    return render(request, 'ecorpin/index.html', context)

def privacy(request):
    info = Endpoint_info.objects.get(end_point="Privacy Policy")
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/privacy.html', context)

def team(request):
    info = Endpoint_info.objects.get(end_point="Team")
    ecorpians = list(Ecorpian.objects.all().order_by('joinDate'))
    context = {
        'info':info,
        'ecorpians_list':ecorpians,
    }
    return render(request, 'ecorpin/team.html', context)

def tou(request):
    info = Endpoint_info.objects.get(end_point="Terms of Use")
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/tou.html', context)

def contact(request):
    info = Endpoint_info.objects.get(end_point="Contact")
    # logic for dynamic org. contact details from database
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/contact.html', context)

def careers(request):
    info = Endpoint_info.objects.get(end_point='Careers')
    # Logic for the opening carrier or description here
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/careers.html', context)

def about(request):
    info = Endpoint_info.objects.get(end_point='About')
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/about.html', context)

def maintenance(request):
    info = Endpoint_info.objects.get(end_point='Server Maintenance')
    # logic for maintenance details from database 
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/maintenance.html', context)

def covid(request):
    info = Endpoint_info.objects.get(end_point='Ecorpin Covid-19 Response')
    #covid dynamic details from database - NOTIFICATION 
    context = {
        'info':info,
    }
    return render(request, 'ecorpin/covid.html', context)

def feedback_create(request):
    serverMsg = ''
    info = Endpoint_info.objects.get(end_point='Feedback')
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            print("*******************************************************")
            return HttpResponseRedirect('/')
        else:
            print("-------------------------------------------------------")
    else:
        form = FeedbackForm()
    context = {
        'form': form,
        'info': info,
        }
    return render(request, 'ecorpin/feedback.html', context)

def service(request):
    # logic for the serving data of ecorpin service from database
    return HttpResponse("<h1>Ecorpin Secure Server - Services</h1>")

def search_view(request):
    #logic for the user search 
    pass

ecorpin_corp/templates/ecorpin/about.html
{% extends 'ecorpin/base.html' %}

<!-- Endpoint Information -->
{% if info %}
    {% block titile %} {{ info.title }} {% endblock %}
    {% block end-point %} {{ info.end_point }} {% endblock %}
    {% block side-nav %} {{ info.sideNav }} {% endblock %}

    {% block main-headBox %}
        <h3>About</h3>
        <h1><b>Ecorpin Corporation</b></h1>
        <p>{{ info.main_headBox }}</p>
    {% endblock %}
    {% block edge-headBox %}<h3><b>{{ info.edge_headBox }}</b></h3>{% endblock %}
{% endif %}

{% block content %}
    <div class="aboutUsBox">
        <div class="box1 ">
            <h2><strong>“Hi, We are ecorpians! The electrifying young minds”</strong></h2>
            <br>
            <p>“Based in various Remote Locations in India and on internet, here at Ecorpin
                Corp. we explore, ideate and collaborate with clients to execute and integrate
                digital solutions using the latest in technologies.”</p>
            <p>“Our peoples are what make us different. Ecorpin's creative, technologically
                savvy, curious and restlessly strategic people looking to reimagine and
                transform what is possible.”</p>
        </div>
        <hr>
        <div class="box2" style="text-align: center;">
            <div>“At <strong>Ecorpin Corporation</strong>, we pursue <i><b>research, education, and innovation</b></i>
                with a passion for serious impact.”</div>
            <div>“Ecorpians' is comprised of passionately creative, technologically savvy, curious
                and restlessly strategic people looking for reimagine and transform what is
                possible.”</div>
                <br>
            <div class="labelTitle">
                <h2><br>Our Philosophy<br></h2>
                <br>
                <div>“Transform forward thinking into forward doing.”
                <br>“We strive to awaken the potential of today to build towards a better futeure.” </div>
            </div>
        </div>
    </div>
{% endblock%}

ecorpin_corp/templates/ecorpin/base.html
<!DOCTYPE html>
<html lang="en" class="no-js theme--custom">
<head>
	{% load static %}
	{% block head %}
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title>{% block title %}{% endblock %}</title>

	<meta name="theme-color" content="#ffffff">
	<link rel="stylesheet" href="{% static 'css/baseCSS.css' %}" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

	<style>
		.theme--custom {
			--primary-spot: 220, 169, 64;
			--primary-text: 0, 0, 0;
			--primary-bg: 255, 255, 255;
			--primary-bg--alt: 255, 255, 255;
			--secondary-spot: 244, 221, 141;
			--secondary-text: 255, 255, 255;
			--secondary-bg: 00, 80, 80;
			--search-spot: 244, 221, 141;
			--search-text: 255, 255, 255;
			--search-bg: 91, 89, 128;
		}

		h2.hidden {
			visibility: hidden;
		}

		.aboutUsBox {
			height: auto;
			color: #004040;
		}

		.box1 {
			color: #004040;
			font-size: 100%;
		}

		.box2 {
			color: #004040;
			font-family: monospace;
			font-size: 100%;
		}

		.search_button {
			padding: 8px 50px;
			border: none;
			background-color: #004040;
			color: #FFF;
			cursor: pointer;
			display: inline-block;
		}

		.search_button:hover {
			background-color: black;
			color: #004040;
		}

		::selection {
			background: #009688;
		}
	</style>
	{% endblock %}
</head>

<body class="tle search">
	<!--Navigation Pannel-->
	<nav class="site-nav">
		<div class="site-nav__width">
			<a class="site-nav__logo-link" href="{% url 'ecorpin:index' %}" style="text-decoration: none; color:#004040">
				<div class="site-nav__title">
					<h2 class="visible"><b> Ecorpin Corporation </b></h2>
				</div>
			</a>
		</div>
	</nav>

	<!--Sub Heading-->
	<div class="search-topper" align="center">
		<div class="headBox">
			<h2 class="hidden">white_space</h2>
			{% block main-headBox %}{% endblock %}
			<h2 class="hidden">white_space</h2>
		</div>
	</div>

	<main class="tle-main" id="main" tabindex="-1" aria-live="polite">
		<div class="tle-content-mod">
			<!--PATH & ENDPOINT-->
			<section class="tle-gutter-container">
				<div class="tle-container">
					<header class="tle-header tle-padding">
						<div class="tle-header__intro">
							<ul class="breadcrumbs">
								<h2 class="hidden"> Ecorpin Corporation </h2>
								<li class="breadcrumb">
									<a class="breadcrumb__link" href="{% url 'ecorpin:index' %}">Home</a>
								</li>
								<li class="breadcrumb">
									<span property="schema:name">{% block end-point %}{% endblock %}</span>
								</li>
							</ul>

							<div class="tle-gutter">
								<h2 class="hidden"> Ecorpin Corporation </h2>
								<h2 class="tle-gutter__title"><span property="schema:name">{% block side-nav %}{% endblock %}</span> </h2>
								<div class="tle-gutter__bg"></div>
							</div>
							<div class="tle-header__intro-text"></div>
						</div>
					</header>
				</div>
			</section>

			<!--PAGE CONTENT-->
			<section>
				<div class="tle-container">
					<div class="tle-row tle-padding">
						<div class="tle-column-12">
							<div class="tle-body-text">
								{% block content %}
								
								{% endblock %}
								<h2>&nbsp;</h2>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</main>

	<!--EDGE Heading-->
	<section>
		<div class="search-topper" align="center">
			<h2 class="hidden">Ecorpin Corporation</h2>
			{% block edge-headBox %}{% endblock %}
			<h2 class="hidden">Ecorpin Corporation</h2>
		</div>
	</section>

	<!--  Ecorpin Corporation footer pannel  -->
	<footer class="site-footer">
		<ul class="site-footer__nav-mod">
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'ecorpin:service' %}">Services</a>
			</li>
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'lab:index' %}">Ecorpin Lab.</a>
			</li>
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'service_access:login' %}">Service Access</a>
			</li>
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'service_access:contact_request' %}">Start Project</a>
			</li>
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'ecorpin:contact' %}">Contact Us</a>
			</li>
			<li class="site-footer__nav__link-item">
				<a class="site-footer__nav__link js-nav-item " href="{% url 'ecorpin:about' %}">About Us</a>
			</li>
		</ul>

		<div class="site-footer__utility-mod">
			<!--Organization Details-->
			<p class="site-footer__name"><a href="{% url 'ecorpin:index' %}"> Ecorpin Corporation </a></p>
			<div class="site-footer__contact-info">
				<a target="_blank" class="site-footer__contact-info-link">INDIA, Asia Pacific</a>
			</div>
		</div>
	</footer>
</body>

</html>

ecorpin_corp/templates/ecorpin/contact.html
{% extends 'ecorpin/base.html' %}

<!-- Endpoint Information -->
{% if info %}
    {% block titile %} {{ info.title }} {% endblock %}
    {% block end-point %} {{ info.end_point }} {% endblock %}
    {% block side-nav %} {{ info.sideNav }} {% endblock %}
    {% block main-headBox %}<h2><b>{{ info.main_headBox }}</b></h2>{% endblock %}
    {% block edge-headBox %}<h4><b>{{ info.edge_headBox }}</b></h4>{% endblock %}
{% endif %}

<!-- Content Block -->
{% block content %}
    <div class="tle-body-text">
        <h2>Contact Info</h2>
        <p><b>Ecorpin Corporation</b><br> INDIA, Pecific Asia</p>

        <p><a href="tel:+916295173968" title="Call Us">Mob.: <u>+91 6295173968</u></a><br>
            <a href="mailto:ecorpin.help@gmail.com" title="Write Us">Email: <u>ecorpin.help@gmail.com</u></a>
        </p>

        <h3><br> Have an idea!.. start a project with <a href="{% url 'ecorpin:team' %}" title="Ecorpin Developers"><u>#ecorpians</u></a></h3>
        <p> Tell us a bit about your project or idea, so we can start a conversation.<br>
            <button class="search_button"><a href="{% url 'service_access:contact_request' %}">START A PROJECT WITH US</a></button>
        </p>

        <h3><br> About Ecorpin Corporation</h3>
        <p>Know more at our <a href="{% url 'ecorpin:about' %}" title="About Ecorpin"> <u> About Us</u></a> page. <br> For questions about Ecorpin,
            email us at <a href="mailto:ecorpin.help@gmail.com" title="Write Us"><u>ecorpin.help@gmail.com</u></a>.
        </p>

        <h3><br> Directory</h3>
        <div>You can find people, products, and services by using the main search function on this site (<a href="{% url 'ecorpin:maintenance' %}"><u>go to Search Pannel</u></a>).</div>

        <h3><br> Website Feedback</h3>
        <div>We welcome your feedback about the Ecorpin Corporation. <br>
            We'd love to know what you think about our services so that we can make sure the experience is the best it can be.<br>
            <button class="search_button">
                <a href="{% url 'ecorpin:feedback' %}">LEAVE FEEDBACK</a>
            </button>
        </div>

        <h3><br> Help Us</h3>
        <div> Questions, corrections, and suggestions should be directed to <a ref="mailto:ecorpin.help@gmail.com" title="Write Us"><u>ecorpin.help@gmail.com</u></a>.</div>

        <h3><br> Follow Us</h3>
        <p>The Ecorpin Network explores new and better methods for Ecorpin to spark the right connections within Ecorpin and between 
            Ecorpin and the world. We tailor communications experiences to the passions and needs of those who wish to join, support, or 
            understand our mission and its pursuit.
        </p>
    </div>
{% endblock%}

ecorpin_corp/templates/ecorpin/feedback.html
{% extends 'ecorpin/base.html' %}

<!-- Endpoint Information -->
{% if info %}
    {% block titile %} {{ info.title }} {% endblock %}
    {% block end-point %} {{ info.end_point }} {% endblock %}
    {% block side-nav %} {{ info.sideNav }} {% endblock %}
    {% block main-headBox %}<h2><b>{{ info.main_headBox }}</b></h2><br>
        <p>We'd love to know what you think about our services so that we can make sure the experience is the best it can be.</p>
    {% endblock %}
    {% block edge-headBox %}<h4><b>{{ info.edge_headBox }}</b></h4>{% endblock %}
{% endif %}

{% block content %}
    <form name="feedback_form" action="{% url 'ecorpin:feedback' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="search_button" id="submit_feedback_data" type="submit">Submit Response</button>
    </form>

    <script>
        document.getElementById("submit_feedback_data").addEventListener("click", function () {
            // data validation in form
            var n = document.forms["feedback_form"]["visitor_name"].value;
            var e = document.forms["feedback_form"]["visitor_email"].value;
            var o = document.forms["feedback_form"]["visitor_organization"].value;
            var m = document.forms["feedback_form"]["feedback_msg"].value;

            if (n && e && o && m) {
                // on submission successful message 
                let timerInterval
                Swal.fire({
                    title: "thank's for your valuable feedback",
                    html: 'It will close in <b></b> milliseconds.',
                    timer: 2000,
                    timerProgressBar: true,
                    onBeforeOpen: () => {
                        Swal.showLoading()
                        timerInterval = setInterval(() => {
                            const content = Swal.getContent()
                            if (content) {
                                const b = content.querySelector('b')
                                if (b) {
                                    b.textContent = Swal.getTimerLeft()
                                }
                            }
                        }, 100)
                    },
                    onClose: () => {
                        clearInterval(timerInterval)
                    }
                });
            }
        });
    </script>
{% endblock%}

ecorpin_corp/templates/ecorpin/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	<title>Ecorpin Corporation</title>
	<link rel="stylesheet" href="{% static 'css/w3.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
	<style>
		body,
		h1,
		h2,
		h3,
		h4,
		h5 {
			font-family: "Raleway", sans-serif
		}

		.w3-third img {
			margin-bottom: -6px;
			opacity: 0.8;
			cursor: pointer
		}

		.w3-third img:hover {
			opacity: 1
		}

		.search_button {
			padding: 8px 50px;
			border: none;
			background-color: #004040;
			color: #FFF;
			cursor: pointer;
			display: inline-block;
		}

		.search_button:hover {
			background-color: black;
			color: #004040;
		}

		a {
			text-decoration: none;
		}

		.ec-bg-Color {
			background-color: #005050;
		}

		ul {
			display: block;
		}

		li {
			display: inline;
			margin-top: 10px;
			margin-left: 2px;
			margin-right: 2px;
			font-size: 14px;
		}

		::selection {
			background: #009688;
		}
	</style>
</head>

<body class="w3-light-grey w3-content" style="max-width:1600px">
	<!-- Sidebar/menu -->
	<nav class="w3-sidebar w3-bar-block w3-white w3-animate-left w3-text-grey w3-collapse w3-top w3-display-container"
		style="z-index:3;width:300px;font-weight:bold" id="mySidebar">
		<a href="{% url 'ecorpin:index' %}"><h3 class="w3-padding-32 w3-center w3-pale-green w3-text-teal"><b>Ecorpin Corporation</b></h3></a>
		<a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-padding w3-hide-large">CLOSE</a>
		<a href="{% url 'service_access:contact_request' %}" onclick="w3_close()" class="w3-bar-item w3-button">Start Project</a>
		<a href="{% url 'lab:index' %}" onclick="w3_close()" class="w3-bar-item w3-button">Ecorpin Lab.</a>
		<a href="{% url 'service_access:login' %}" onclick="w3_close()" class="w3-bar-item w3-button">Service Access</a>
		<a href="{% url 'ecorpin:maintenance' %}" onclick="w3_close()" class="w3-bar-item w3-button">Ecorpin AR/VR</a>

		<div class="w3-display-bottomleft w3-left-align w3-white">
			<p class="w3-medium w3-margin w3-text-teal">Ecorpin Corporation <br> INDIA, Pacific Asia</p>
			<ul class="w3-stretch ">
				<li><a href="{% url 'ecorpin:service' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Service</a></li>
				<li><a href="{% url 'works:projects' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Work</a></li>
				<li><a href="{% url 'ecorpin:about' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">About</a></li>
				<li><a href="{% url 'ecorpin:contact' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Contact</a></li>
				<li><a href="{% url 'ecorpin:team' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Team</a></li>
				<br>
				<li><a href="{% url 'ecorpin:careers' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Careers</a></li>
				<li><a href="{% url 'ecorpin:privacy' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Privacy</a></li>
				<li><a href="{% url 'ecorpin:tou' %}" class="w3-border-bottom w3-hover-border-teal w3-hover-text-teal">Terms Of Use</a></li>
			</ul>
		</div>
	</nav>

	<!-- Top menu on small screens -->
	<header class="w3-container w3-top w3-hide-large w3-white w3-xlarge w3-padding-16">
		<span class="w3-left w3-padding">Ecorpin Corporation</span>
		<a href="javascript:void(0)" class="w3-right w3-button w3-white" onclick="w3_open()">☰</a>
	</header>

	<!-- Overlay effect when opening sidebar on small screens -->
	<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

	<!-- !PAGE CONTENT! -->
	<div class="w3-main" style="margin-left:300px">
		<!-- Push down content on small screens -->
		<div class="w3-hide-large" style="margin-top:83px"></div>

		<div class="w3-container w3-black w3-padding-16 ">
			<h5><b>Ecorpins' Covid Response</b>: <a class="w3-hover-text-red" href="{% url 'ecorpin:covid' %}" title="Covid-19">Click here for information on adapting to Covid-19 and keeping connected.</a></h5>
		</div>

		<!-- Photo grid -->
		<div class="w3-row">
			<img class="w3-image" src="{% static 'spotlight/laser.jpg' %}" style="width:100%" onclick="onClick(this)" alt="Laser Technology">
		</div>

		<!--Spotlight section -->
		{% if latest_spotlight %}
		<div class="w3-container ec-bg-Color w3-center w3-text-light-grey w3-padding-32" id="spotlight">
			<h5>Spotlight : Ecorpin Lab.</h5>
			<div class="w3-content w3-justify" style="max-width:800px">
				<h2>“{{ latest_spotlight.spotlight_info }}”</h2><br>
				<p>“{{ latest_spotlight.spotlight_text }}”</p><br>

				<hr class="w3-opacity">
				{{ spotlightData.spotlight_date }}
				<hr class="w3-opacity">
				<div>
					<h4 class="">We inspire our extraordinary team, and they inspire us right back.</h4>
					<p class="w3-text-blue-gray">Have an idea!.. start a <a class="w3-text-sand" title="Hire Us" href="{% url 'service_access:contact_request' %}">project</a>
						with <a class="w3-text-sand" title="Ecorpin Developers" href="{% url 'ecorpin:team' %}">#ecorpians</a><br>
						<a href="{% url 'service_access:contact_request' %}" class="search_button w3-boarder" style="text-decoration: none;">START A PROJECT</a>
					</p>
				</div>
			</div>

		</div>
		{% else %}
			<h3 class="w3-red w3-xxlarge w3-text-white w3-center">No spotlight is available...</h3>
		{% endif %}

		<!-- Footer -->
		<footer class="w3-container w3-padding-32 w3-blue-grey w3-hide-small">
			<div class="w3-row-padding">
				<div class="w3-half w3-text-white w3-center">
					<h3 class="w3-wide">Ecorpin Corporation</h3>
					<p class="w3-padding">“Transform forward thinking into forward doing.”<br>“We explore, ideate and collaborate
						with clients to execute and integrate digital solutions using the latest in virtual and augmented reality technologies.”
					</p>
				</div>

				<div class="w3-half w3-text-black">
					<h3><strong>#ecorpians :</strong> Ecorpin Developers</h3>
					<p>We've passion for serious impact. We make new ways of seeing, and we see new ways of making. We inspire our extraordinary team, and they inspire us right back. 
					</p>
				</div>
			</div>
		</footer>

		<div class="w3-black w3-center w3-padding-24">Engineered by <a href="https://devbuggs.pythonanywhere.com/" title="Bhagwan Singh" target="_blank" class="w3-hover-opacity">Bhagwan Singh</a></div>
	</div>

	<script>
		// Script to open and close sidebar
		function w3_open() {
			document.getElementById("mySidebar").style.display = "block";
			document.getElementById("myOverlay").style.display = "block";
		}

		function w3_close() {
			document.getElementById("mySidebar").style.display = "none";
			document.getElementById("myOverlay").style.display = "none";
		}

		// Modal Image Gallery
		function onClick(element) {
			document.getElementById("img01").src = element.src;
			document.getElementById("modal01").style.display = "block";
			var captionText = document.getElementById("caption");
			captionText.innerHTML = element.alt;
		}

	</script>
</body>

</html>