ecorpin_corp/ecorpin/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'ecorpin'
urlpatterns = [
    path('', views.index_ecorpin, name='index'),
    path('service/', views.service, name='service'),
    path('feedback/', views.feedback_create, name='feedback'),
    path('about/', views.about, name='about'),
    path('careers/', views.careers, name='careers'),
    path('contact/', views.contact, name='contact'),
    path('terms_of_use/', views.tou, name='tou'),
    path('team/', views.team, name='team'),
    path('privacy/', views.privacy, name='privacy'),
    path('server_maintenance/', views.maintenance, name='maintenance'),
    path('covid/', views.covid, name='covid'),
]

ecorpin_corp/ecorpin_corp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

# favicon view of the web server
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('ecorpin.urls')),
    path('', include('service_access.urls')),
    path('', include('bbit.urls')),
    path('', include('works.urls')),
    path('', include('payment.urls')),
    path('', include('lab.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecorpin_corp/lab/urls.py
from django.urls import path

from .views import index 

app_name = 'lab'

urlpatterns = [
    path('lab', index, name="index"),
]

ecorpin_corp/payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'
urlpatterns = [
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('paymentinfo/', views.paymentCallback, name='payment_info'),

]

ecorpin_corp/service_access/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url 

# import views here
from . import views

app_name = 'service_access'
urlpatterns = [
    path('contact_request/', views.contact_request, name='contact_request'),
    path('service_login/', views.login_view, name="login"),
    path('logout/', views.service_logout, name="logout"),
    path('dashboard/', views.ServiceDashboard.as_view(), name="dashboard"),
    path('profile/', views.ServiceUserProfile.as_view(), name="profile"),
]

ecorpin_corp/works/urls.py
from django.urls import path
from . import views

app_name = 'works'
urlpatterns = [
    path('work/', views.projects_view, name='projects'),

]

ecorpin_corp/service_access/models.py
import datetime
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

# Create your models here.
class TypeReq(models.Model):
    medium = models.CharField(max_length=20)

    def __str__(self):
        return self.medium

class ContactRequest(models.Model):
    project_title = models.CharField(max_length=200)
    project_idea = models.TextField()
    contact_date = models.DateTimeField('Contact Date')
    contact_email = models.EmailField(max_length=200)
    contact_mobile = models.IntegerField()
    contact_name = models.CharField(max_length=100)
    contact_type = models.ForeignKey(TypeReq, on_delete=models.CASCADE)
    contact_status = models.BooleanField(default=False)

    def __str__(self):
        return self.project_title

# extending existing User model into ServiceUser for seperate active ecorpin service user 
class ServiceUser(models.Model):
    user = models.OneToOneField(User, related_name='service_user', on_delete=models.CASCADE)
    service_id = models.CharField(max_length=12, unique=True, blank=False)
    
    def __str__(self):
        return "{}".format(self.service_id)

# class for default development phases (Initiating, Planning, Design, Development, Testing, Production)
class DevelopmentStatus(models.Model):
    phase_name = models.CharField(max_length=50)

    def __str__(self):
        return "{} Phase".format(self.phase_name)

#class for default Status (Active or Inactive)
class ServiceStatus(models.Model):
    status_name = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return self.status_name

# class for user services
class Service(models.Model):
    service_id = models.ForeignKey(ServiceUser, related_name='projects', on_delete=models.CASCADE)
    email = models.EmailField()
    contact = models.CharField(max_length=15, blank=True)
    title = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=500, blank=True)
    technology = models.CharField(max_length=50, blank=True)
    framework = models.CharField(max_length=50, blank=True)
    platform = models.CharField(max_length=50, blank=True)
    live_url = models.URLField(blank=True)
    payment_status = models.CharField(max_length=50, blank=True) # need focus
    development_phase = models.OneToOneField(DevelopmentStatus, on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey(ServiceStatus, on_delete=models.SET_NULL, null=True)
    start_date = models.DateField(default=timezone.now)
    deadline = models.DateField(blank=True)
    dedicatedTime = models.IntegerField()
    notification = models.CharField(max_length=150, default=None, blank=True)

    def __str__(self):
        return "{}".format(self.title)

ecorpin_corp/works/models.py
from django.db import models
import datetime

# Create your models here.

'''
class ProjectsDetail(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    url = models.CharField(max_length=100)
    platform = models.CharField(max_length=50)
    technology = models.CharField(max_length=50)
    framework = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(url_name, name=self.name)
''' 

class ClientReview(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    msg = models.CharField(max_length=600)
    

ecorpin_corp/service_access/forms.py
from django import forms

from .models import ContactRequest


class ContactRequestForm(forms.ModelForm):
    class Meta:
        model = ContactRequest
        fields = ('contact_name', 'contact_mobile', 'contact_email', 'contact_type', 'contact_date', 'project_title', 'project_idea')
        labels = {
            'project_title': 'Title',
            'project_idea': 'Description',
            'contact_type': 'Contact Medium',
            'contact_date': 'Contact Date',
            'contact_email': 'Email',
            'contact_mobile': 'Phone',
            'contact_name': 'Name'
        }

ecorpin_corp/service_access/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse 

from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.core.mail import send_mail


from service_access.models import ContactRequest, ServiceUser, Service
from ecorpin.models import Endpoint_info
from .forms import ContactRequestForm
from payment.models import Transaction

# Create your views here.
def contact_request(request):
    serverMsg = ''
    if request.method == 'POST':
        form = ContactRequestForm(request.POST)
        if form.is_valid():
            form.save()
            serverMsg = "Contact Request is received. We'll contact you shortly. "
            #return render(request, 'service_access/contact_request.html', { 'data':serverMsg })
            return render(request, 'service_access/new_project.html', { 'data':serverMsg })
        else:
            print("--------> SOMETHING WENT WRONG.")
            serverMsg = "Something went wrong! please try again... "
            #return render(request, 'service_access/contact_request.html', { 'data':serverMsg })
            return render(request, 'service_access/new_project.html', { 'data':serverMsg })
    else:
        form = ContactRequestForm()
        context = { 'form': form, }
        #return render(request, 'service_access/contact_request.html', context)
        return render(request, 'service_access/new_project.html', context)

@login_required
def service_logout(request):
    logout(request)
    return redirect("service_access:login")

def login_view(request):
    if request.method == 'POST':
        sid = request.POST.get('serviceId')
        pwd = request.POST.get('password')
        prefix = sid[:7]
        if str(prefix) == str("EC-56020"):
            print("Service Id Validation Done")
        else:
            print("Service Id Validation Failed!")
        service_user_obj = ServiceUser.objects.filter(service_id = sid)
        if service_user_obj is not None:
            print("-------------------> Service available for the request id")
            print("-------------------> ", service_user_obj)
            print("-------------------> ", service_user_obj[0].user.username)
            username = service_user_obj[0].user.username
            user = authenticate(request, username=username, password=pwd)
            if user is not None:
                login(request, user)
                print("Logging in user")
                return redirect('service_access:dashboard')
            return HttpResponse("Something went wrong in our server! #ecorpians ")
        else:
            print("-------------------> No user found..")
    return render(request, 'service_access/service_login.html')

class ServiceDashboard(LoginRequiredMixin, View):
    template_name='service_access/dashboard.html'
    def get(self, request):
        # <view logic>
        service_user_id = ServiceUser.objects.get(user = request.user.id)
        service_list = Service.objects.filter(service_id = service_user_id)
        payment_list = Transaction.objects.filter(user=request.user)
        info = Endpoint_info.objects.get(end_point="Dashboard")
        context = {
            'payment_list': payment_list,
            'service_list': service_list,
            'info':info,
        }
        return render(request, 'service_access/dashboard.html', context)
    def post(self, request):
        #<view logic>
        user = request.user
        data = request.POST
        service_user_id = ServiceUser.objects.get(user = request.user.id)
        service_list = Service.objects.filter(service_id = service_user_id)
        payment_list = Transaction.objects.filter(user=request.user)
        info = Endpoint_info.objects.get(end_point="Dashboard")
        #print('----------------> ', data)
        user_mail = request.user.email
        user_subject = str(data['catogary'] +" | "+user.first_name+' '+user.last_name + " | "+ data['phone'] + " | Service Access")
        #print('----------------> ', user_subject)
        user_message = data['message']
        #print('----------------> ', user_message)
        print("mail :: ", user_mail, "\nsubject :: ", user_subject, "\nmessage :: ", user_message)
        email_from = settings.EMAIL_HOST_USER
        recipitent_list = [user_mail, ]
        send_mail(user_subject, user_message, email_from, recipitent_list)
        context = {
            'payment_list': payment_list,
            'service_list': service_list,
            'info':info,
            'mail_response': 'response submitted! thank you..'
        }
        return render(request, 'service_access/dashboard.html', context)
        
class ServiceUserProfile(LoginRequiredMixin, View):
    template_name = 'service_access/profile.html'

    def get(self, request):
        #return reverse('ecorpin:team')
        #print("--------------------------- Service User Profile ---------------------------")
        info = Endpoint_info.objects.get(end_point="Profile")
        context = {
            'info':info,
        }
        return render(request, 'service_access/profile.html', context)

    def post(self, request):
        # logic for service user profile post method
        pass

class ServiceUpdateView():
    # logic for the service/profile/information update request
    def get(self, request):
        # login for service update get method
        pass

    def post(self, request):
        # login for service update get method
        pass

    pass

class ServiceSupportView():
    #logic for the specific user support history with org. support
    pass

ecorpin_corp/templates/service_access/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/w3.css' %}">
        <link rel="stylesheet" href="{% static 'css/flatUIcolor.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        {% block style %}
            <style>
                box{display: none;}
                uibox{color: firebrick;}
            </style>
        {% endblock %}
    </head>
    <body class="w3-dark-gray">
        <!-- Sidebar/menu -->
        <nav class="w3-sidebar w3-bar-block w3-flat-midnight-blue w3-animate-right w3-top w3-text-light-grey w3-large" style="z-index:3;width:250px;font-weight:bold;display:none;right:0;" id="mySidebar">
            <a href="javascript:void()" onclick="w3_close()" class="w3-bar-item w3-button w3-center w3-padding-32">CLOSE</a> 
            {% if request.user.is_authenticated %}
            <a href="{% url 'service_access:dashboard' %}" class="w3-bar-item w3-button w3-center w3-padding-16">Dashboard</a> 
            <a href="{% url 'service_access:profile' %}" class="w3-bar-item w3-button w3-center w3-padding-16">Profile</a>
            <a href="{% url 'service_access:contact_request' %}" class="w3-bar-item w3-button w3-center w3-padding-16">Project</a> 
            <a href="#" class="w3-bar-item w3-button w3-center w3-padding-16">Support</a>
            <a href="{% url 'service_access:logout' %}" class="w3-bar-item w3-button w3-center w3-padding-16">Logout</a>
            {% endif %}
        </nav>
        <!-- Top menu on small screens -->
        <header class="w3-container w3-top w3-white w3-xlarge w3-padding-16">
            <a href="{% url 'service_access:dashboard' %}" class="w3-span w3-btn w3-hover-none w3-left w3-padding w3-text-teal">Service Access</a>
            <a href="javascript:void(0)" class="w3-right w3-button w3-white w3-text-teal" onclick="w3_open()">☰</a>
        </header>
        <!-- Overlay effect when opening sidebar on small screens -->
        <div class="w3-overlay w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
        
        <!-- !PAGE CONTENT! -->
        <div class="w3-main w3-content" style="max-width:1600px;margin-top:83px">
            <div class="w3-row w3-flat-green-sea">
                <div class="w3-half">
                    <!-- Project List  -->
                    {% if service_list %}
                            <div class="w3-dropdown-hover w3-quarter w3-flat-green-sea">
                                <select class="w3-select w3-border w3-border-black w3-teal w3-bar-item w3-button" id="select_project">
                                    <option disabled selected>Select project</option>
                                    {% for service in service_list %}
                                        <option id="{{ service.id }}" value="{{ service.id }} uibox" class="w3-button w3-bar-item w3-flat-wet-asphalt">{{ service.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                    {% endif %}
                    <p class="w3-padding-small w3-center w3-text-sand w3-large w3-twothird">have a look! We're building your dream...</p>
                </div>
                <ol class="w3-ol w3-right w3-border-left">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'service_access:dashboard' %}" class="w3-btn w3-border-bottom	w3-border-white w3-hover-border-black w3-serif">dashboard</a>
                    <a href="{% url 'service_access:profile' %}" class="w3-btn w3-border-bottom	w3-border-white w3-hover-border-black w3-serif">profile</a>
                    <li class="w3-btn w3-border-bottom	w3-border-white w3-hover-border-black w3-serif">notification</li>
                    <li class="w3-btn w3-border-bottom	w3-border-white w3-hover-border-black w3-serif">support</li>
                    <a href="{% url 'payment:pay' %}" class="w3-btn w3-border-bottom w3-border-white w3-hover-border-black w3-serif">payment</a>
                    <a href="{% url 'service_access:logout' %}" class="w3-btn w3-border-bottom	w3-border-white w3-hover-border-black w3-serif">logout</a>
                    {% else %}
                        <h1 class="w3-red">Failed Logic</h1>
                    {% endif %}
                </ol>
            </div>
            {% block content %}

            {% endblock %}
        </div>
        
        <script>
            // Script to open and close sidebar
            function w3_open() {
              document.getElementById("mySidebar").style.display = "block";
              document.getElementById("myOverlay").style.display = "block";
            }
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
              document.getElementById("myOverlay").style.display = "none";
            }
            // jQuery for dropdown
            $(document).ready(function(){
                $("select").change(function(){
                    $(this).find("option:selected").each(function(){
                        var optionValue = $(this).attr("value");
                        if(optionValue){
                            $(".box").not("." + optionValue).hide();
                            $("." + optionValue).show();
                        } else{
                            $(".box").hide();
                        }
                    });
                }).change();
            });
        </script>
    </body>
</html>

ecorpin_corp/templates/service_access/dashboard.html
<!DOCTYPE html>
{% extends 'service_access/base.html' %}
{% block title %}{{ info.title }}{% endblock %}

{% block style %}
    <style>
        body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
        .w3-quarter img{margin-bottom: -6px; cursor: pointer}
        .w3-quarter img:hover{opacity: 0.6; transition: 0.3s}
        /* .myListSlide {display:none;} */
        option{
            font-family: 'Courier New', Courier, monospace;
            font-size: large;
            padding: 10px;
        }
        box{
            display: none;
        }
        uibox{
            color: firebrick;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="w3-row w3-flat-wet-asphalt w3-padding-32 w3-padding-64 ">
        {% for service in service_list %}
            <div id="{{ service.id }}" class="myListSlide w3-half w3-card-4 w3-rightbar w3-border-teal w3-padding-large box uibox">
                <h1 class="w3-text-teal w3-serif">{{ service.title }}</h1>
                <h4 class="w3-text-sand">{{ service.description }}</h4>
                <table class="w3-table w3-bordered  w3-half">
                    <tr>
                        <td>Service Id</td>
                        <td><strong>{{ service.service_id  }}</strong></td>
                    </tr>
                    <tr>
                        <td>Contact</td>
                        <td><strong>{{ service.contact }}</strong></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><strong>{{ service.email }}</strong></td>
                    </tr>
                    <tr>
                        <td>Platform</td>
                        <td><strong>{{ service.platform }}</strong></td>
                    </tr>
                    <tr>
                        <td>Technology</td>
                        <td><strong>{{ service.technology }}</strong></td>
                    </tr>
                    <tr>
                        <td>Framework</td>
                        <td><strong>{{ service.framework }}</strong></td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td><strong>{{ service.status }}</strong></td>
                    </tr>
                </table>
                <table class="w3-table w3-bordered w3-bar-block w3-half">
                    <tr>
                        <td>Development</td>
                        <td><strong>{{ service.development_phase }}</strong></td>
                    </tr>
                    <tr>
                        <td>Start Date</td>
                        <td><strong>{{ service.start_date }}</strong></td>
                    </tr>
                    <tr>
                        <td>Deadline</td>
                        <td>{{ service.deadline }}</td>
                    </tr>
                    <tr>
                        <td>Time (in Hrs.)</td>
                        <td><strong>{{ service.dedicatedTime }}</strong></td>
                    </tr>
                    <tr>
                        <td>Notification</td>
                        <td><strong>{{ service.notification }}</strong></td>
                    </tr>
                    <tr>
                        <td>Payment Status</td>
                        <td><strong>{{ service.payment_status }}</strong></td>
                    </tr>
                    <tr>
                        <td>Live URL</td>
                        <td><a class="w3-button w3-bar-item w3-border" id ="dashboard-button" href="{{ service.live_url }}" target="_blank">Visit Now</a></td>
                    </tr>
                </table>
            </div>
        {% endfor %}
        <div class="w3-third w3-card-4 w3-leftbar w3-border-teal w3-padding-large w3-right">
            <h3 class="w3-text-teal w3-large">Notification's</h3>
            <ul class="w3-ul">
                {% for service in service_list %}
                    <li class="w3-text-blue-gray w3-small w3-hover-blue-gray"><b class="w3-text-white"> {{ service.title }}</b> - {{ service.development_phase }} {{ service.notification }}<span class="close w3-cursor w3-text-red w3-right">&times;</span></li>
                {% endfor %}
            </ul>
            <br >
            <h3 class="w3-text-teal w3-large">{{ request.user.service_user.service_id }} recent payments</h3>
            <ul class="w3-ul">
                {% for payment in payment_list %}
                    <li class="w3-text-blue-gray w3-small w3-hover-pale-red">{{ payment.order_id }} - {{ payment.amount }} <span class="close w3-cursor w3-text-black w3-right">&times;</span></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="w3-container w3-flat-midnight-blue w3-padding-64">
        {% if mail_response %}
            <div class="w3-row w3-center w3-xxlarge w3-serif">{{ mail_response }}</div>
        {% else %}
        <div class="w3-third w3-padding-large">
            <h3 class=""><strong>request a call back.</strong></h3>
            <p class="w3-medium w3-serif w3-padding-medium">Would you like to speak one of our technical consultants over the phone? Just submit your details and we'll be in touch shortly.</p>
        </div>
        <div class="w3-twothird w3-padding-small">
            <h6 class="w3-large w3-serif w3-text-white w3-margin-left">I would like to discuss:</h6>
            <form class="w3-row w3-padding-small w3-medium w3-bar" method="POST">
                {% csrf_token %}
                <div class="w3-half w3-padding-small">
                    <input type="text" class="w3-input w3-serif " name="catogary" id="id_catogary" placeholder="choose"><br>
                    <input type="text" class="w3-input w3-serif" name="phone" id="id_phone" placeholder="Phone number">
                </div>
                <div class="w3-half w3-padding-small">
                    <input type="text" class="w3-input w3-serif" name="name" id="id_name" placeholder="Name"><br>
                    <input type="text" class="w3-input w3-serif" name="message" id="id_message" placeholder="Message">
                </div>
                <input type="submit" class="w3-button w3-bar-item w3-border w3-margin-top" value="submit" style="margin-left:6px;">
            </form>
        </div>
        {% endif %}
    </div>

    <div class="w3-row w3-center w3-text-sand w3-red w3-large w3-padding-32">{{ info.edge_headBox }}</div>

    <script>
        var slideIndex = 0;
        // carousel();

        // function carousel() {
        //     var i;
        //     var x = document.getElementsByClassName("myListSlide");
        //     for (i = 0; i < x.length; i++) {
        //         x[i].style.display = "none"; 
        //     }
        //     slideIndex++;
        //     if (slideIndex > x.length) {slideIndex = 1} 
        //     x[slideIndex-1].style.display = "block"; 
        //     setTimeout(carousel, 5000); 
        // }
        // close element
        var closebtns = document.getElementsByClassName("close");
        var i;
        for (i = 0; i < closebtns.length; i++) {
        closebtns[i].addEventListener("click", function() {
            this.parentElement.style.display = 'none';
        });
        }
    </script>
 {% endblock %}

ecorpin_corp/templates/service_access/new_project.html
{% extends 'service_access/base.html' %}
{% block title %}Start project | Ecorpin{% endblock %}
{% block style %}
	<style>
		label{
			display: none;
		}
		input, select, textarea{
			margin-bottom: 10px;
			margin-left: 5px;
			margin-right: 5px;
			/* width: 50% !important; */
		}
		textarea {
			padding: 12px;
			border: none;
			/* margin: 5px 0; */
			display: inline-block;
			font-size: 17px;
			line-height: 20px;
			text-decoration: none;
		}
		#submit_btn{
			margin-left: 5px;
			margin-right: 5px;
		}
	</style>
{% endblock %}

{% block content %}

<div>
	<div class="w3-container w3-flat-midnight-blue w3-padding-64">
		<div class="w3-third w3-padding-large">
			<h3 class=""><strong>request a call back.</strong></h3>
			<p class="w3-medium w3-serif w3-padding-medium">tell us a bit about your project or idea, so we can start a conversation...</p>
		</div>
		<div class="w3-twothird ">
			<h6 class="w3-large w3-serif w3-text-white w3-margin-left">tell us a bit about your project or idea, so we can start a conversation..</h6>
			<!-- <form class="w3-row w3-padding-small w3-medium w3-bar" method="POST">
				<div class="w3-half w3-padding-small">
					<input type="text" class="w3-input w3-serif" name="catogary" id="id_catogary" placeholder="choose"><br>
					<input type="text" class="w3-input w3-serif" name="phone" id="id_phone" placeholder="Phone number"><br>
					<input type="text" class="w3-input w3-serif" name="project_title" id="id_title" placeholder="project title">
				</div>
				<div class="w3-half w3-padding-small">
					<input type="text" class="w3-input w3-serif" name="name" id="id_name" placeholder="Name"><br>
					<input type="email" class="w3-input w3-serif" name="email" id="id_email" placeholder="Email"><br>
					<input type="text" class="w3-input w3-serif" name="phone" id="id_phone" placeholder="Date & Time">
				</div>

				<input type="submit" class="w3-button w3-bar-item w3-border w3-margin-top" value="submit" style="margin-left:6px;">
				<button class="button button3" type="submit">Let's Start Together</button>
			</form> -->
			<form action="{% url 'service_access:contact_request' %}" class="w3-row w3-medium w3-bar" method="POST" autocomplete="off">
				{% csrf_token %}
				{{ form.as_p }}
				<button id="submit_btn" class="w3-button w3-third w3-border" type="submit">Let's Start Together</button>
			</form>
		</div>
	</div>

  <script>
    var ContactName = document.getElementById("id_contact_name");
    var ContactMobileNumber = document.getElementById("id_contact_mobile");
    var ContactEmailAddress = document.getElementById("id_contact_email");
    var ContactType = document.getElementById("id_contact_type");
    var ContactDateTime = document.getElementById("id_contact_date");
    var ProjectTitle = document.getElementById("id_project_title");
    var ContactProjectIdea = document.getElementById("id_project_idea");

    ContactName.setAttribute("placeholder", "your name");
	ContactName.classList.add("w3-third", "w3-input");

	ContactMobileNumber.classList.add("w3-third", "w3-input");
    ContactMobileNumber.setAttribute("type", "tel");
    ContactMobileNumber.setAttribute("pattern", "[0-9]{10}");
    ContactMobileNumber.setAttribute("placeholder", "e.g. 999999XXXX");

	ContactEmailAddress.setAttribute("placeholder", "your email");
	ContactEmailAddress.classList.add("w3-third", "w3-input");

    ProjectTitle.setAttribute("placeholder", "project title");
	ProjectTitle.classList.add("w3-third", "w3-input");

    ContactProjectIdea.setAttribute("placeholder", "Tell us a bit about your project or idea, so we can start a conversation.");
    ContactProjectIdea.classList.add("w3-input", "w3-twothird");

    ContactDateTime.classList.add("w3-input", "w3-third");
    ContactDateTime.setAttribute("type", "datetime-local");

    ContactType.classList.add("w3-select", "w3-pale-red", "w3-third");

    // Open and close sidebar
    function w3_open() {
      document.getElementById("mySidebar").style.width = "100%";
      document.getElementById("mySidebar").style.display = "block";
    }
    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
    }
  </script>
</div>
{% endblock %}